export const GET_PASSWORDS_SUCCESS = 'GET_PASSWORDS_SUCCESS';
export const GET_PASSWORDS_FAIL = 'GET_PASSWORDS_FAIL';
export const GET_PASSWORD_BY_ID_SUCCESS = 'GET_PASSWORD_BY_ID_SUCCESS';
export const GET_PASSWORD_BY_ID_FAIL = 'GET_PASSWORD_BY_ID_FAIL';
export const DECRYPT_PASSWORD_SUCCESS = 'DECRYPT_PASSWORD_SUCCESS';
export const DECRYPT_PASSWORD_FAIL = 'DECRYPT_PASSWORD_FAIL';
export const DELETE_PASSWORD_SUCCESS = 'DELETE_PASSWORD_SUCCESS';
